# Generated by Django 3.2.9 on 2022-04-22 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
