# Generated by Django 3.2.9 on 2022-04-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_grade_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade_level',
        ),
    ]
