# Generated by Django 3.2.9 on 2022-05-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220506_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_data', to='user.user'),
        ),
    ]
