# Generated by Django 3.2.9 on 2022-02-02 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_by'],
            },
        ),
        migrations.AlterField(
            model_name='boardanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='board.boardquestion'),
        ),
        migrations.CreateModel(
            name='BoardReply2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.boardanswer')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.boardreply')),
            ],
            options={
                'ordering': ['created_by'],
            },
        ),
        migrations.AddField(
            model_name='boardreply',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='board.boardanswer'),
        ),
    ]
