# Generated by Django 3.2.9 on 2022-02-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20220202_0543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
