# Generated by Django 3.2.9 on 2022-02-03 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('board', '0005_auto_20220203_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardreply',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='user.user'),
        ),
        migrations.AlterField(
            model_name='boardquestion',
            name='slug',
            field=models.SlugField(default=uuid.UUID('595338cf-dcbe-45ad-a500-6d4e53a06534')),
        ),
        migrations.AlterField(
            model_name='boardreply',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='board.boardanswer'),
        ),
        migrations.DeleteModel(
            name='BoardReply2',
        ),
    ]
