# Generated by Django 3.2.9 on 2022-02-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20220203_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardquestion',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boardquestion',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
