# Generated by Django 3.2.9 on 2022-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20220214_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardquestion',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
