# Generated by Django 3.2.9 on 2022-02-17 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0008_boardquestion_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardanswer',
            name='good',
        ),
        migrations.RemoveField(
            model_name='boardquestion',
            name='good',
        ),
        migrations.AlterField(
            model_name='boardanswer',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='BoardLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='board.boardanswer')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='board.boardquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='user.user')),
            ],
        ),
    ]
