# Generated by Django 3.2.9 on 2022-03-01 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0008_boardquestion_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardanswer',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='boardquestion',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='boardquestion',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boardquestion',
            name='slug',
            field=models.SlugField(),
        ),
    ]
