# Generated by Django 3.2.9 on 2022-03-03 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0009_auto_20220301_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardQuestionLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_num', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='board.boardanswer')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='liked_num', to='board.boardquestion')),
                ('user', models.ManyToManyField(default=None, related_name='liked_num', to='user.User')),
            ],
        ),
    ]
