# Generated by Django 3.2.9 on 2022-03-01 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0009_auto_20220301_0501'),
    ]
