# Generated by Django 3.2.9 on 2022-02-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0009_auto_20220217_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardliked',
            name='good',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='boardliked',
            name='user',
        ),
        migrations.AddField(
            model_name='boardliked',
            name='user',
            field=models.ManyToManyField(related_name='liked', to='user.User'),
        ),
    ]
