# Generated by Django 3.2.9 on 2022-02-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0010_auto_20220217_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAnswerLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(blank=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerliked', to='board.boardanswer')),
                ('user', models.ManyToManyField(related_name='answerliked', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='BoardQuestionLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(blank=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionliked', to='board.boardquestion')),
                ('user', models.ManyToManyField(related_name='questionliked', to='user.User')),
            ],
        ),
        migrations.DeleteModel(
            name='BoardLiked',
        ),
    ]
