# Generated by Django 3.2.9 on 2022-03-03 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0010_boardquestionliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardquestionliked',
            name='answer',
        ),
        migrations.CreateModel(
            name='BoardAnswerLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_num', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_answer', to='board.boardanswer')),
                ('user', models.ManyToManyField(default=None, related_name='liked_answer', to='user.User')),
            ],
        ),
    ]
