# Generated by Django 3.2.9 on 2022-03-06 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0011_auto_20220306_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcentertag',
            name='question',
        ),
        migrations.AddField(
            model_name='boardcentertag',
            name='question',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='cnter_tag', to='board.BoardQuestion'),
        ),
        migrations.AlterField(
            model_name='boardcentertag',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='cnter_tag', to='user.User'),
        ),
    ]
