# Generated by Django 3.2.9 on 2022-02-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20220217_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardquestionliked',
            name='question',
        ),
        migrations.RemoveField(
            model_name='boardquestionliked',
            name='user',
        ),
        migrations.AddField(
            model_name='boardanswer',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardquestion',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BoardAnswerLiked',
        ),
        migrations.DeleteModel(
            name='BoardQuestionLiked',
        ),
    ]
