# Generated by Django 3.2.9 on 2022-03-06 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0014_auto_20220306_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardusertag',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='board.boardcentertag'),
        ),
        migrations.AlterField(
            model_name='boardusertag',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_tag', to='user.user'),
        ),
    ]
