# Generated by Django 3.2.9 on 2022-03-07 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0015_auto_20220306_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcentertag',
            name='parent_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnter_tag', to='board.boardparentcentertag'),
        ),
        migrations.AlterField(
            model_name='boardusertag',
            name='used_num',
            field=models.IntegerField(default=0),
        ),
        
    ]
