# Generated by Django 3.2.9 on 2022-03-10 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0017_auto_20220307_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardquestion',
            name='good',
        ),
        migrations.AddField(
            model_name='boardquestion',
            name='post_on_going',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boardquestion',
            name='select_best_on_going',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardquestion',
            name='vote_on_going',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boardcentertag',
            name='parent_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_tag', to='board.boardparentcentertag'),
        ),
        migrations.AlterField(
            model_name='boardcentertag',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, related_name='center_tag', to='user.User'),
        ),
    ]
