# Generated by Django 3.2.9 on 2022-03-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0018_auto_20220310_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardquestion',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='boardusertag',
            name='status_handle',
            field=models.CharField(choices=[('used', 'used'), ('viewed', 'viewed')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boardusertag',
            name='viewed_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='boardusertag',
            name='used_num',
            field=models.IntegerField(default=1),
        ),
        
    ]
