# Generated by Django 3.2.9 on 2022-03-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0019_auto_20220314_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardusertag',
            name='status_handle',
        ),
        migrations.AddField(
            model_name='boardusertag',
            name='total_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boardusertag',
            name='used_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boardusertag',
            name='viewed_num',
            field=models.IntegerField(default=0),
        ),
    ]
