# Generated by Django 3.2.9 on 2022-03-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0021_boardanswerliked_userfavoritequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavoritequestion',
            name='liked_num',
        ),
    ]
