# Generated by Django 3.2.9 on 2022-03-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_thumbnail'),
        ('board', '0022_auto_20220321_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardanswer',
            name='on_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardquestion',
            name='on_answer',
            field=models.BooleanField(default=False),
        ),
        
    ]
