# Generated by Django 3.2.9 on 2022-05-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_ipdata_user'),
        ('board', '0023_auto_20220323_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardquestion',
            name='on_reply',
            field=models.BooleanField(default=False),
        ),
        
    ]
