# Generated by Django 3.2.9 on 2021-11-06 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersAnsewer',
            new_name='UsersAnswer',
        ),
    ]
