# Generated by Django 3.2.9 on 2021-11-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_usersansewer_usersanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='question',
            name='field',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='module',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
