# Generated by Django 3.2.9 on 2021-11-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20211109_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='queztion_count',
            new_name='question_count',
        ),
    ]
