# Generated by Django 3.2.9 on 2021-11-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_queztion_count_quiz_question_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_count',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_count',
        ),
    ]
