# Generated by Django 3.2.9 on 2021-11-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20211121_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(default=False),
        ),
    ]
