# Generated by Django 3.2.9 on 2021-11-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20211121_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quizzes/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(),
        ),
    ]
