# Generated by Django 3.2.9 on 2022-04-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_rename_srarus_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_select',
            field=models.IntegerField(default=0),
        ),
    ]
