# Generated by Django 3.2.9 on 2022-04-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_question_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='level',
            new_name='quiz_level',
        ),
    ]
