# Generated by Django 3.2.9 on 2022-04-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20220420_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiztaker',
            old_name='quiz_practice_num',
            new_name='practice_take_num',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='user_status',
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='user_status',
            field=models.ManyToManyField(blank=True, to='quiz.UserStatus'),
        ),
    ]
