# Generated by Django 3.2.9 on 2022-04-22 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20220422_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='user_status',
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='user_status',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.userstatus'),
        ),
    ]
