# Generated by Django 3.2.9 on 2022-04-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20220422_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='taken_num',
            field=models.IntegerField(default=0),
        ),
    ]
