# Generated by Django 3.2.9 on 2022-04-23 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20220423_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='user_status',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='quiz_taker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to='quiz.quiztaker'),
        ),
    ]
