# Generated by Django 3.2.9 on 2022-04-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20220423_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='is_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='is_false',
            field=models.IntegerField(default=0),
        ),
    ]
