# Generated by Django 3.2.9 on 2022-04-25 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_grade_level'),
        ('quiz', '0025_auto_20220423_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taker', to='user.user'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.parentquiz'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.parentstatus'),
        ),
    ]
