# Generated by Django 3.2.9 on 2022-04-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20220423_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.parentquiz'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.parentstatus'),
        ),
    ]
