# Generated by Django 3.2.9 on 2022-04-24 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_grade_level'),
        ('quiz', '0026_auto_20220424_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taker', to='user.user'),
        ),
    ]
