# Generated by Django 3.2.9 on 2022-04-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20220425_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentstatus',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.parentquiz'),
        ),
    ]
