# Generated by Django 3.2.9 on 2022-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20220424_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='status',
            field=models.ManyToManyField(blank=True, to='quiz.ParentStatus'),
        ),
    ]
