# Generated by Django 3.2.9 on 2022-04-30 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_alter_parentstatus_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='test_take_num',
            field=models.IntegerField(default=1),
        ),
    ]
