# Generated by Django 3.2.9 on 2022-04-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_auto_20220424_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='status',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.parentstatus'),
        ),
    ]
