# Generated by Django 3.2.9 on 2022-04-30 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220430_0722'),
        ('quiz', '0028_auto_20220430_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.parentquiz'),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taker', to='user.user'),
        ),
    ]
