# Generated by Django 3.2.9 on 2022-04-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20220425_0226'),
        ('quiz', '0029_auto_20220424_1019'),
    ]

    operations = [
    ]
