# Generated by Django 3.2.9 on 2022-05-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20220430_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='max_grade',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='max_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
