# Generated by Django 3.2.9 on 2022-05-19 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_ipdata_user'),
        ('quiz', '0030_auto_20220517_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num', models.IntegerField(default=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('question', models.ManyToManyField(related_name='my_quiz', to='quiz.Question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_quiz', to='user.user')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
