# Generated by Django 3.2.9 on 2022-04-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20220425_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='quiz_taker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to='quiz.quiztaker'),
        ),
    ]
