# Generated by Django 3.2.9 on 2022-05-19 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_ipdata_user'),
        ('quiz', '0031_myquiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myquiz',
            options={},
        ),
        migrations.RemoveField(
            model_name='myquiz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='myquiz',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='myquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_quiz', to='user.user'),
        ),
        migrations.CreateModel(
            name='MyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('my_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_question', to='quiz.myquiz')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_question', to='quiz.question')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
