# Generated by Django 3.2.9 on 2022-05-19 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20220519_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myquestion',
            name='my_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_question', to='quiz.myquiz'),
        ),
        migrations.AlterField(
            model_name='myquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_question', to='quiz.question'),
        ),
    ]
