# Generated by Django 3.2.9 on 2022-06-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('actualErrorName', models.CharField(blank=True, max_length=100, null=True)),
                ('actualErrorMessage', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
