# Generated by Django 3.2.9 on 2022-06-17 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='checke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logger',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logger',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
